version: "3"
services:
    rest-api:
        image: "sanagama/mssql-restapi"
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
          MSSQL_HOST: "db"
          MSSQL_USERNAME: "sa"
          MSSQL_PASSWORD: "Yukon900"
        
    db:
        image: "microsoft/mssql-server-linux:2017-GA"
        environment:
            SA_PASSWORD: "Yukon900"
            ACCEPT_EULA: "Y"